### ISSUE TITLE
CSS не работает :)

### ISSUE THREAD

**Issue by fingli** [AlexTalker/AlexTalker.github.io#1]
With the current configuration Firefox loads only the text content. Currently GitHub uses http**s** to their pages, in your configuration (/_includes/header.html) CSS and JS files are loaded with `{{site.baseurl | prepend:site.url}}` which serves the content through plain http. Thus way the browser considers this behavior as "mixed content" and blocks the plain http sources. 

Use one of following ways to load the content:
`<link rel="stylesheet" href="{{ "/css/main.css" | prepend: site.baseurl }}">`
or
`<link rel="stylesheet" href="{{ site.baseurl }}/css/main.css">`

Also: 
Add `<!DOCTYPE html>` before the `<html>` tag

**Comment by AlexTalker** [comment]
Oh, yep, I guess I've fix that.
Thanks!

**Comment by AlexTalker** [comment]
Finally got it:

![2016-02-29-202043_1366x768_scrot](https://cloud.githubusercontent.com/assets/3531127/13402582/04aa95fa-df22-11e5-8cf2-a8015d0d727e.png)

Thanks for reporting.

**Comment by fingli** [comment]
Nice :) 

Там есть что то еще в конце. Но не знаю откуда  этот `</div>` после `</html>` появляестя. Смотри на картинке
![div](https://cloud.githubusercontent.com/assets/420475/13404222/5aa2e526-df21-11e5-9946-1f6cbcea1a6d.png)

**Comment by AlexTalker** [comment]
@fingli seems like in `_layouts/page.html` include of footer happens before closing div...need more investigation :smile:
